In [3]:
%load_ext autoreload
%autoreload 2
from OmegaGomoku import *
import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [62]:
board = np.asarray([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
tboard = np.full((board.shape[0] + 2, board.shape[0] + 2), 3, np.int32)
tboard[1:board.shape[0] + 1, 1:board.shape[1] + 1] = board
board, tboard

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[3, 3, 3, 3, 3],
        [3, 1, 2, 3, 3],
        [3, 4, 5, 6, 3],
        [3, 7, 8, 9, 3],
        [3, 3, 3, 3, 3]]))

In [63]:
board[board == 5] = 10

In [64]:
board

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])